### ISSUE TITLE
Style patient info section record page

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/ShotBot#10]
Style the section of the page with patient information (Name, DOB, age, ID#)
- Fix size and position of card
- Hide all info except name, DOB, age, ID# (for now at least)
- Remove 'Edit' link at bottom of page
- Move 'Back' link to header, style as button

![record](https://cloud.githubusercontent.com/assets/2693690/15730258/ee0703aa-281f-11e6-9793-26f6d396b29f.png)

**Comment by lostmarinero** [comment]
resolved, new styling up to date
