### ISSUE TITLE
Screenshots of each page

### ISSUE THREAD

**Issue by jessonawhim** [codeforamerica/ShotBot#19]
To share with city partners, etc.

**Comment by lostmarinero** [comment]
![screen shot 2016-06-06 at 2 12 37 pm](https://cloud.githubusercontent.com/assets/4044722/15872237/413c8ce8-2cad-11e6-841f-674efa57e9b6.png)
![screen shot 2016-06-06 at 2 12 31 pm](https://cloud.githubusercontent.com/assets/4044722/15872240/4140134a-2cad-11e6-96ab-40f465993ae5.png)
![screen shot 2016-06-06 at 2 12 24 pm](https://cloud.githubusercontent.com/assets/4044722/15872238/413f1ca6-2cad-11e6-9466-1d910cda2d29.png)
![screen shot 2016-06-06 at 2 11 45 pm](https://cloud.githubusercontent.com/assets/4044722/15872242/414a4298-2cad-11e6-96ed-7c1a4b26a520.png)
![screen shot 2016-06-06 at 2 11 38 pm](https://cloud.githubusercontent.com/assets/4044722/15872239/413f12c4-2cad-11e6-9aa6-1fadccd80d4a.png)
![screen shot 2016-06-06 at 2 11 32 pm](https://cloud.githubusercontent.com/assets/4044722/15872241/4140f288-2cad-11e6-8826-72db3f1d0b2f.png)

**Comment by lostmarinero** [comment]
Shared in the issue @jessonawhim
