### ISSUE TITLE
Design explanation/recommendation box

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/ShotBot#41]
Add a space on shot record (web and print) to explain why a status (due/not due) was determined.

**Comment by racheledelman** [comment]
@lostmarinero once you've figured it out, can you add details about what type and format of information we'll be able to include here?

**Comment by lostmarinero** [comment]
I think we will be able to have a list of the next shots due and when

If they are past due, then the when will be today and then the schedule moving forward

format wise, i am unsure as of now... but i think if you have ideas on how that would look visually, making some mocks might be a good idea

Also - if there is an error (such as a shot given too early for it to be valid), i believe this will be singled out as well. But not sure! Sorry:/

**Comment by racheledelman** [comment]
![image](https://cloud.githubusercontent.com/assets/2693690/16930632/f49b1a48-4cf1-11e6-9646-186aef423ec1.png)

Right now the explanation area looks like this. It can definitely be tweaked depending on the info available. This method would require categorizing the types of errors and writing a template for each (the copy here is a first pass). We could start as simply as just listing the incorrect or missing vax and it's associate date (ie "Invalid vaccine: Tdap, 1/17/15"), and relying on the nurse to figure out why.

**Comment by racheledelman** [comment]
Just to reiterate: the wording in the mock up is BAD and CONFUSING and is a placeholder.
